version: '3.7'

services:
  web:
    container_name: cloud-way
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8003:8000"
    networks:
      - webnet

networks:
  webnet:
