# Generated by Django 4.1.7 on 2023-04-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CeoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ceo_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Moments/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('icon_class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicingCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='servicing_countries')),
                ('description', models.CharField(max_length=500)),
                ('banner', models.ImageField(upload_to='servicing_countries_banner')),
                ('details', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('feature_3', models.CharField(max_length=200)),
                ('benefits_of_cloud_way', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_image', models.ImageField(upload_to='university_image')),
                ('university_name', models.CharField(max_length=100)),
                ('desciption', models.CharField(max_length=100)),
                ('university_details', models.TextField()),
                ('university_specialities_1', models.CharField(max_length=100)),
                ('university_specialities_1_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_2', models.CharField(max_length=100)),
                ('university_specialities_2_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_3', models.CharField(max_length=100)),
                ('university_specialities_3_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_4', models.CharField(max_length=100)),
                ('university_specialities_4_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_5', models.CharField(max_length=100)),
                ('university_specialities_5_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicingcountries')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='cource_we_provide')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.university')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicingcountries')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courseprovide')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
        ),
    ]
