# Generated by Django 4.1.7 on 2023-05-31 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Card',
            },
        ),
        migrations.CreateModel(
            name='Accreditations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Accreditations/')),
            ],
            options={
                'verbose_name_plural': 'Accreditations',
            },
        ),
        migrations.CreateModel(
            name='CeoMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('ceo_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ceo Message',
            },
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Moments/')),
            ],
            options={
                'verbose_name_plural': 'Moments',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('icon_class_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ServicingCountries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='servicing_countries')),
                ('description', models.CharField(max_length=500)),
                ('banner', models.ImageField(upload_to='servicing_countries_banner')),
                ('details', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('feature_3', models.CharField(max_length=200)),
                ('benefits_of_cloud_way', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Servicing Countries',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('course_name_and_university', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('student_image', models.ImageField(upload_to='testimonials_student_image')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university_image', models.ImageField(upload_to='university_image')),
                ('university_name', models.CharField(max_length=100)),
                ('desciption', models.CharField(max_length=100)),
                ('university_details', models.TextField()),
                ('university_specialities_1', models.CharField(max_length=100)),
                ('university_specialities_1_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_2', models.CharField(max_length=100)),
                ('university_specialities_2_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_3', models.CharField(max_length=100)),
                ('university_specialities_3_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_4', models.CharField(max_length=100)),
                ('university_specialities_4_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university_specialities_5', models.CharField(max_length=100)),
                ('university_specialities_5_icon', models.ImageField(upload_to='university_detail_icons')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicingcountries')),
            ],
            options={
                'verbose_name_plural': 'University',
            },
        ),
        migrations.CreateModel(
            name='CourseProvide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.university')),
            ],
            options={
                'verbose_name_plural': 'Course Provide',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicingcountries')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courseprovide')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
