# Generated by Django 4.1.7 on 2023-04-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accreditations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprovide',
            name='icon',
        ),
    ]
