# Generated by Django 4.1.7 on 2023-04-06 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testimonials_rename_ceoabout_aboutcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='student_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='testimonials_student_image'),
            preserve_default=False,
        ),
    ]
